<a href="https://colab.research.google.com/github/KarunaBaruwal/CMP7005-Hypertension-Analytics/blob/main/CMP7005_Hypertension_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#from google.colab import drive

#drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
username = "Karuna Baruwal"   # <- change this
repo = "CMP7005-Hypertension-Analytics"             # <- change this

!git clone https://github.com/KarunaBaruwal/CMP7005-Hypertension-Analytics.git
%cd CMP7005-Hypertension-Analytics
%ls

Cloning into 'CMP7005-Hypertension-Analytics'...
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 12 (delta 3), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (12/12), 126.11 KiB | 3.15 MiB/s, done.
Resolving deltas: 100% (3/3), done.
/content/CMP7005-Hypertension-Analytics/CMP7005-Hypertension-Analytics/CMP7005-Hypertension-Analytics
CMP7005_Hypertension_Analysis.ipynb  hypertension_dataset_5000.csv  README.md

In [ ]:
file_path = "hypertension_dataset_5000.csv"
df = pd.read_csv(file_path)

In [ ]:
df.head()

,Age,Gender,BMI,Waist_Circumference_cm,Salt_Intake,Physical_Activity,Alcohol_Consumption,Smoking_Status,Stress_Level,Sleep_Hours,Family_History_HTN,Creatinine_mg_dL,Fasting_Glucose_mg_dL,Cholesterol_mg_dL,Systolic_BP_mmHg,Diastolic_BP_mmHg,BP_Category,Hypertension
0,83.2,Male,24.6,92.5,Normal,Light,NaN,Former,Moderate,7.5,No,0.98,89.0,201.4,119,65,Normal,No
1,69.0,Female,26.1,76.6,Very High,Light,NaN,Former,Low,6.5,Yes,NaN,83.2,178.9,132,81,Stage 1 Hypertension,Yes
2,45.1,Male,24.5,86.4,High,Sedentary,Occasional,Former,Very High,6.1,No,1.02,86.0,163.2,131,87,Stage 1 Hypertension,Yes
3,45.5,Male,25.6,85.2,Normal,Active,Moderate,Current,High,6.4,Yes,0.86,80.5,146.0,127,88,Stage 1 Hypertension,Yes
4,41.7,Male,28.7,97.4,High,Active,Moderate,Current,High,6.9,No,1.27,97.0,210.6,120,78,Elevated,No

In [ ]:
print("Number of patients:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of patients: 5000
Number of columns: 18

In [ ]:
# Display column names and data types
df.info()

# Count missing values in each column
display(df.isnull().sum())

# Count exact duplicate rows
print("Duplicate rows:", df.duplicated().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Age                     5000 non-null   float64
 1   Gender                  5000 non-null   object
 2   BMI                     5000 non-null   float64
 3   Waist_Circumference_cm  4846 non-null   float64
 4   Salt_Intake             4939 non-null   object
 5   Physical_Activity       5000 non-null   object
 6   Alcohol_Consumption     3632 non-null   object
 7   Smoking_Status          5000 non-null   object
 8   Stress_Level            4909 non-null   object
 9   Sleep_Hours             4837 non-null   float64
 10  Family_History_HTN      5000 non-null   object
 11  Creatinine_mg_dL        4867 non-null   float64
 12  Fasting_Glucose_mg_dL   4821 non-null   float64
 13  Cholesterol_mg_dL       4841 non-null   float64
 14  Systolic_BP_mmHg        5000 non-null   int64
 15  Diastolic_BP_mmHg       5000 non-null   int64
 16  BP_Category             5000 non-null   object
 17  Hypertension            5000 non-null   object
dtypes: float64(7), int64(2), object(9)
memory usage: 703.3+ KB

Age                          0
Gender                       0
BMI                          0
Waist_Circumference_cm     154
Salt_Intake                 61
Physical_Activity            0
Alcohol_Consumption       1368
Smoking_Status               0
Stress_Level                91
Sleep_Hours                163
Family_History_HTN           0
Creatinine_mg_dL           133
Fasting_Glucose_mg_dL      179
Cholesterol_mg_dL          159
Systolic_BP_mmHg             0
Diastolic_BP_mmHg            0
BP_Category                  0
Hypertension                 0
dtype: int64

Duplicate rows: 0

Missing values Analysis

In [ ]:
missing_summary = pd.DataFrame({
    'Missing Count': df.isnull().sum(),
    'Missing Percentage': df.isnull().mean() * 100
})

missing_summary = missing_summary[
    missing_summary['Missing Count'] > 0
]

missing_summary = missing_summary.sort_values(
    by='Missing Percentage',
    ascending=False
)

display(missing_summary.round(2))

                        Missing Count  Missing Percentage
Alcohol_Consumption              1368               27.36
Fasting_Glucose_mg_dL             179                3.58
Sleep_Hours                       163                3.26
Cholesterol_mg_dL                 159                3.18
Waist_Circumference_cm            154                3.08
Creatinine_mg_dL                  133                2.66
Stress_Level                       91                1.82
Salt_Intake                        61                1.22

In [ ]:
df['Alcohol_Missing'] = df['Alcohol_Consumption'].isnull()
missing_by_htn = pd.crosstab(
    df['Hypertension'],
    df['Alcohol_Missing'],
    normalize='index'
) * 100
display(missing_by_htn.round(2))

Alcohol_Missing  False  True
Hypertension
No               70.25  29.75
Yes              77.09  22.91

In [ ]:

pd.crosstab(
    df['Hypertension'],
    df['Alcohol_Consumption'].isna(),
    margins=True
)

Alcohol_Consumption  False  True   All
Hypertension
No                    2283   967  3250
Yes                   1349   401  1750
All                   3632  1368  5000

In [ ]:
df = df.drop(columns=['Alcohol_Missing'])

In [ ]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Age,5000.0,48.648320,16.908037,18.20,34.575,47.40,61.60,89.20
BMI,5000.0,27.876320,4.254628,16.20,24.900,27.70,30.80,43.50
Waist_Circumference_cm,4846.0,89.417623,11.410790,54.00,81.500,89.10,97.10,126.40
Sleep_Hours,4837.0,6.850444,1.042016,3.50,6.200,6.90,7.50,10.50
Creatinine_mg_dL,4867.0,0.942063,0.171618,0.51,0.820,0.93,1.05,1.68
Fasting_Glucose_mg_dL,4821.0,93.301058,12.753358,62.10,84.500,92.20,100.90,173.40
Cholesterol_mg_dL,4841.0,187.219851,30.546704,105.00,165.600,187.30,207.60,288.30
Systolic_BP_mmHg,5000.0,116.826600,16.385269,88.00,104.000,115.00,128.00,181.00
Diastolic_BP_mmHg,5000.0,74.259600,9.483849,50.00,67.000,74.00,81.00,110.00

In [ ]:
numeric_summary = df.describe().T

display(
    numeric_summary[['count', 'mean', 'min', 'max']]
    .round(2)
)

                         count    mean     min     max
Age                     5000.0   48.65   18.20   89.20
BMI                     5000.0   27.88   16.20   43.50
Waist_Circumference_cm  4846.0   89.42   54.00  126.40
Sleep_Hours             4837.0    6.85    3.50   10.50
Creatinine_mg_dL        4867.0    0.94    0.51    1.68
Fasting_Glucose_mg_dL   4821.0   93.30   62.10  173.40
Cholesterol_mg_dL       4841.0  187.22  105.00  288.30
Systolic_BP_mmHg        5000.0  116.83   88.00  181.00
Diastolic_BP_mmHg       5000.0   74.26   50.00  110.00

In [ ]:
invalid_bp = (
    df['Systolic_BP_mmHg'] <= df['Diastolic_BP_mmHg']
).sum()

print("Records requiring BP consistency review:", invalid_bp)

Records requiring BP consistency review: 0

In [ ]:
categorical_cols = df.select_dtypes(
    include=['object', 'category']
).columns

for col in categorical_cols:
    print(f"\nColumn: {col}")
    display(df[col].value_counts(dropna=False))

Column: Gender

Gender
Female    2581
Male      2419
Name: count, dtype: int64

Column: Salt_Intake

Salt_Intake
Normal       1696
High         1597
Very High    1011
Low           635
NaN            61
Name: count, dtype: int64

Column: Physical_Activity

Physical_Activity
Light        1678
Sedentary    1327
Moderate     1258
Active        737
Name: count, dtype: int64

Column: Alcohol_Consumption

Alcohol_Consumption
Occasional    1910
NaN           1368
Moderate      1231
Heavy          491
Name: count, dtype: int64

Column: Smoking_Status

Smoking_Status
Never      2805
Former     1440
Current     755
Name: count, dtype: int64

Column: Stress_Level

Stress_Level
Moderate     1844
High         1410
Low           844
Very High     811
NaN            91
Name: count, dtype: int64

Column: Family_History_HTN

Family_History_HTN
No     3218
Yes    1782
Name: count, dtype: int64

Column: BP_Category

BP_Category
Normal                  2713
Stage 1 Hypertension    1147
Stage 2 Hypertension     603
Elevated                 537
Name: count, dtype: int64

Column: Hypertension

Hypertension
No     3250
Yes    1750
Name: count, dtype: int64

In [ ]:
categorical_summary = []

for col in categorical_cols:
    categories = df[col].dropna().unique()
    categorical_summary.append({
        'Variable': col,
        'Unique Categories': len(categories),
        'Category Names': ', '.join(map(str, categories)),
        'Missing Values': df[col].isna().sum()
    })
display(pd.DataFrame(categorical_summary))

,Variable,Unique Categories,Category Names,Missing Values
0,Gender,2,"Male, Female",0
1,Salt_Intake,4,"Normal, Very High, High, Low",61
2,Physical_Activity,4,"Light, Sedentary, Active, Moderate",0
3,Alcohol_Consumption,3,"Occasional, Moderate, Heavy",1368
4,Smoking_Status,3,"Former, Current, Never",0
5,Stress_Level,4,"Moderate, Low, Very High, High",91
6,Family_History_HTN,2,"No, Yes",0
7,BP_Category,4,"Normal, Stage 1 Hypertension, Elevated, Stage ...",0
8,Hypertension,2,"No, Yes",0

In [ ]:
bp_relationship = pd.crosstab(
    df['BP_Category'],
    df['Hypertension']
)

display(bp_relationship)

Hypertension            No   Yes
BP_Category
Elevated               537     0
Normal                2713     0
Stage 1 Hypertension     0  1147
Stage 2 Hypertension     0   603

In [ ]:

df.groupby('BP_Category')[
    ['Systolic_BP_mmHg', 'Diastolic_BP_mmHg']
].agg(['min', 'max', 'mean']).round(2)

                     Systolic_BP_mmHg              Diastolic_BP_mmHg       \
                                  min  max    mean               min  max
BP_Category
Elevated                          120  129  124.03                55   79
Normal                             88  119  104.93                50   79
Stage 1 Hypertension              105  139  126.60                59   89
Stage 2 Hypertension              116  181  145.34                66  110


                       mean
BP_Category
Elevated              73.92
Normal                68.05
Stage 1 Hypertension  81.76
Stage 2 Hypertension  88.22

In [ ]:

df.loc[
    (df['BP_Category'] == 'Stage 1 Hypertension') &
    (df['Systolic_BP_mmHg'] < 120),
    ['Systolic_BP_mmHg', 'Diastolic_BP_mmHg', 'BP_Category']
].head(10)

     Systolic_BP_mmHg  Diastolic_BP_mmHg           BP_Category
41                113                 81  Stage 1 Hypertension
61                115                 80  Stage 1 Hypertension
65                119                 80  Stage 1 Hypertension
83                112                 84  Stage 1 Hypertension
125               117                 84  Stage 1 Hypertension
134               109                 82  Stage 1 Hypertension
148               111                 81  Stage 1 Hypertension
167               114                 82  Stage 1 Hypertension
197               107                 82  Stage 1 Hypertension
206               118                 80  Stage 1 Hypertension