<a href="https://colab.research.google.com/github/KarunaBaruwal/CMP7005-Hypertension-Analytics/blob/main/CMP7005_Hypertension_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
file_path = "/content/drive/MyDrive/CMP7005_Hypertension_Project/hypertension_dataset_5000.csv"
df = pd.read_csv(file_path)

In [5]:
df.head()

,Age,Gender,BMI,Waist_Circumference_cm,Salt_Intake,Physical_Activity,Alcohol_Consumption,Smoking_Status,Stress_Level,Sleep_Hours,Family_History_HTN,Creatinine_mg_dL,Fasting_Glucose_mg_dL,Cholesterol_mg_dL,Systolic_BP_mmHg,Diastolic_BP_mmHg,BP_Category,Hypertension
0,83.2,Male,24.6,92.5,Normal,Light,NaN,Former,Moderate,7.5,No,0.98,89.0,201.4,119,65,Normal,No
1,69.0,Female,26.1,76.6,Very High,Light,NaN,Former,Low,6.5,Yes,NaN,83.2,178.9,132,81,Stage 1 Hypertension,Yes
2,45.1,Male,24.5,86.4,High,Sedentary,Occasional,Former,Very High,6.1,No,1.02,86.0,163.2,131,87,Stage 1 Hypertension,Yes
3,45.5,Male,25.6,85.2,Normal,Active,Moderate,Current,High,6.4,Yes,0.86,80.5,146.0,127,88,Stage 1 Hypertension,Yes
4,41.7,Male,28.7,97.4,High,Active,Moderate,Current,High,6.9,No,1.27,97.0,210.6,120,78,Elevated,No

In [6]:
print("Number of patients:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of patients: 5000
Number of columns: 18

In [7]:
# Display column names and data types
df.info()

# Count missing values in each column
display(df.isnull().sum())

# Count exact duplicate rows
print("Duplicate rows:", df.duplicated().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Age                     5000 non-null   float64
 1   Gender                  5000 non-null   object
 2   BMI                     5000 non-null   float64
 3   Waist_Circumference_cm  4846 non-null   float64
 4   Salt_Intake             4939 non-null   object
 5   Physical_Activity       5000 non-null   object
 6   Alcohol_Consumption     3632 non-null   object
 7   Smoking_Status          5000 non-null   object
 8   Stress_Level            4909 non-null   object
 9   Sleep_Hours             4837 non-null   float64
 10  Family_History_HTN      5000 non-null   object
 11  Creatinine_mg_dL        4867 non-null   float64
 12  Fasting_Glucose_mg_dL   4821 non-null   float64
 13  Cholesterol_mg_dL       4841 non-null   float64
 14  Systolic_BP_mmHg        5000 non-null   int64
 15  Diastolic_BP_mmHg       5000 non-null   int64
 16  BP_Category             5000 non-null   object
 17  Hypertension            5000 non-null   object
dtypes: float64(7), int64(2), object(9)
memory usage: 703.3+ KB

Age                          0
Gender                       0
BMI                          0
Waist_Circumference_cm     154
Salt_Intake                 61
Physical_Activity            0
Alcohol_Consumption       1368
Smoking_Status               0
Stress_Level                91
Sleep_Hours                163
Family_History_HTN           0
Creatinine_mg_dL           133
Fasting_Glucose_mg_dL      179
Cholesterol_mg_dL          159
Systolic_BP_mmHg             0
Diastolic_BP_mmHg            0
BP_Category                  0
Hypertension                 0
dtype: int64

Duplicate rows: 0